[package]
name = "gobblet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
int-enum = "0.4"
rstest = "0.15.0"
rand = "0.8.5"
uuid = "1.1.2"